# Macros
SRC = src/
SRC_FILES = $(SRC)cell.cpp $(SRC)board.cpp $(SRC)cell1.cpp $(SRC)cell2.cpp $(SRC)cell3.cpp $(SRC)game_of_life.cpp $(SRC)cellx.cpp
OUT = bin/
OUT_FILE = $(OUT)exe
TEST = test/
OUT_FILE_TEST = $(OUT)exe

# Reglas explícitas
default:
	g++ -g $(SRC_FILES) -o $(OUT_FILE_TEST)

run: default 

