# Macros
SRC = src/
SRC_FILES = $(SRC)cell.cpp $(SRC)board.cpp $(SRC)game_of_life.cpp
OUT = bin/
OUT_FILE = $(OUT)exe

# Reglas explícitas
default:
	g++ -g $(SRC_FILES) -o $(OUT_FILE)

run: default 

